name: Publish
run-name: Build theme and publish to Marketplace
on: [push]
jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}/themes
      - run: echo "🍏 This job's status is ${{ job.status }}."